export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCES = 'IMAGE_LIST_SUCCES'
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL'

export const IMAGE_REQUEST = 'IMAGE_REQUEST'
export const IMAGE_SUCCES = 'IMAGE_SUCCES'
export const IMAGE_FAIL = 'IMAGE_FAIL'